language: viml

install:
    # Prepare environment
    - mkdir -p ~/.vim/bundle/repos/github.com
    - mkdir ~/.vim/bundle/repos/github.com/thinca
    - mkdir ~/.vim/bundle/repos/github.com/tyru
    - mkdir ~/Repository
    # Install needed plugins
    - git clone https://github.com/thinca/vim-themis ~/.vim/bundle/repos/github.com/thinca/vim-themis
    - git clone https://github.com/tyru/open-browser.vim ~/.vim/bundle/repos/github.com/tyru/open-browser.vim
    - git clone https://github.com/aiya000/aref-web.vim ~/Repository/aref-web.vim
    - git clone https://github.com/vim/vim ~/vim
    # Build just version vim to ~/bin/vim
    - mkdir ~/bin
    - sudo apt-get install -y gettext libncurses5-dev libacl1-dev libgpm-dev
    - cd ~/vim
    - git checkout v7.4.1689
    - ./configure --with-features=huge --enable-fail-if-missing --prefix=$HOME/bin/vim
    - make
    - make install
    - export THEMIS_VIM=$HOME/bin/vim/bin/vim

before_script:
    - $HOME/bin/vim/bin/vim --version

script:
    - ~/.vim/bundle/repos/github.com/thinca/vim-themis/bin/themis ~/Repository/aref-web.vim/test --reporter spec

branches:
    - master
