language: generic

install:
    # Prepare environment
    - mkdir -p ~/.vim/bundle/repos/github.com
    - mkdir ~/.vim/bundle/repos/github.com/thinca
    - mkdir ~/.vim/bundle/repos/github.com/tyru
    - mkdir ~/Repository
    # Install needed plugins
    - git clone https://github.com/thinca/vim-themis ~/.vim/bundle/repos/github.com/thinca/vim-themis
    - git clone https://github.com/tyru/open-browser.vim ~/.vim/bundle/repos/github.com/tyru/open-browser.vim
    - git clone https://github.com/aiya000/aref-web.vim ~/Repository/aref-web.vim
    # Build just version vim to ~/vim-7.4.1689
    - if [ ! -d ~/vim-7.4.1689/bin ] ; then
      git clone https://github.com/vim/vim /tmp/vim &&
      cd /tmp/vim &&
      git checkout v7.4.1689 &&
      ./configure --prefix=$HOME/vim-7.4.1689 &&
      make &&
      make install;
      fi
    - export THEMIS_VIM=$HOME/vim-7.4.1689/bin/vim

cache:
    directories:
        - $HOME/vim-7.4.1689

before_script:
    - $HOME/vim-7.4.1689/bin/vim --version

script:
    - ~/.vim/bundle/repos/github.com/thinca/vim-themis/bin/themis ~/Repository/aref-web.vim/test --reporter spec

branches:
    - master
